name: CI Check

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run build simulation
        run: echo "✅ Build simulation passed"
